name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Build Sample
      run: dotnet build --configuration Release Sample/Sample.csproj
    - name: Install ldapsearch
      run: sudo apt-get update && sudo apt-get -y install ldap-utils
    - name: Test Sample
      run: dotnet test Sample.Tests/ --collect:"XPlat Code Coverage" -r TestResults/
    - name: Test Gatekeeper.LdapServerLibrary.Tests
      run: dotnet test Gatekeeper.LdapServerLibrary.Tests/ --collect:"XPlat Code Coverage" -r TestResults/
    - name: Test Gatekeeper.LdapServerLibrary.PacketParser.Tests
      run: dotnet test Gatekeeper.LdapServerLibrary.PacketParser.Tests/ --collect:"XPlat Code Coverage" -r TestResults/
    - uses: codecov/codecov-action@v1
      with:
        directory: TestResults/
        fail_ci_if_error: true
        verbose: true
